[package]
name = "nsr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.2"
cty = "0.2.2"
mac_address = "1.1.5"
byte = "0.2"
internet-checksum = "0.2.1"
rand = "0.8.5"
